// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7SrRU8ZdPdeirTav7o4M68DS18KrlRVE',
    appId: '1:1004822563515:web:af37defd6e9d3465d2f79e',
    messagingSenderId: '1004822563515',
    projectId: 'hodorapp-eabe2',
    authDomain: 'hodorapp-eabe2.firebaseapp.com',
    storageBucket: 'hodorapp-eabe2.firebasestorage.app',
    measurementId: 'G-F89N9XLX9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm5423-onWXRK9WtTlluxDBIJOB5kdqQg',
    appId: '1:1004822563515:android:8be12d266527d9ded2f79e',
    messagingSenderId: '1004822563515',
    projectId: 'hodorapp-eabe2',
    storageBucket: 'hodorapp-eabe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL5FQkz6KK6UmZZ7nzrp4oOU2vDh1fuD4',
    appId: '1:1004822563515:ios:9b718dea3f5f3676d2f79e',
    messagingSenderId: '1004822563515',
    projectId: 'hodorapp-eabe2',
    storageBucket: 'hodorapp-eabe2.firebasestorage.app',
    iosClientId: '1004822563515-83rm2o83i2esr7q84si9gbujn4r213vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL5FQkz6KK6UmZZ7nzrp4oOU2vDh1fuD4',
    appId: '1:1004822563515:ios:9b718dea3f5f3676d2f79e',
    messagingSenderId: '1004822563515',
    projectId: 'hodorapp-eabe2',
    storageBucket: 'hodorapp-eabe2.firebasestorage.app',
    iosClientId: '1004822563515-83rm2o83i2esr7q84si9gbujn4r213vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7SrRU8ZdPdeirTav7o4M68DS18KrlRVE',
    appId: '1:1004822563515:web:bdb2cb581d67dbd6d2f79e',
    messagingSenderId: '1004822563515',
    projectId: 'hodorapp-eabe2',
    authDomain: 'hodorapp-eabe2.firebaseapp.com',
    storageBucket: 'hodorapp-eabe2.firebasestorage.app',
    measurementId: 'G-6N6BPJMT91',
  );
}
